  type Post {
    _id: ID!
    title: String!
    content: String!
    author: User!
  }

  input PostData {
    title: String!
    content: String!
    author: ID!
  }

  type Query {
    posts: [Post!]!
    post(id: ID!): Post
  }

  type Mutation {
    createPost(data: PostData!): Post,
    updatePost(id: ID!, data: PostData!): Post,
    deletePost(id: ID!): Boolean
  }